version : "3"

services:
  rest_api:
    build:
      dockerfile: Dockerfile
    links:
      - "db:mysqldb"
    ports: 
      - "5000:5000"
    container_name: flask_rest_api
    depends_on:
      - db

  db:
    image: mysql
    volumes:
     - ./dbdata:/var/lib/mysql
    
    environment:
      - MYSQL_ROOT_PASSWORD=${password}
      - MYSQL_DATABASE=${database}
    ports:
      - 3306:3306
    container_name: mysql_db




